In [1]:
import pandas as pd 
# Read data from file 'filename.csv' 
# (in the same directory that your python process is based)
# Control delimiters, rows, column names with read_csv (see later) 
df = pd.read_csv("object.csv") 
# Preview the first 5 lines of the loaded data 
df.head()

,Prediction_1,Prediction_2,Prediction_3,Prediction_4,Prediction_5,Prediction_6,Prediction_7,Prediction_8,Prediction_9,Prediction_10
0,seashore,lakeside,promontory,web_site,valley,beacon,breakwater,castle,cliff,monitor
1,black_widow,walking_stick,ant,long-horned_beetle,mantis,sunglass,necklace,sunglasses,harvestman,hook
2,cash_machine,packet,barbershop,menu,book_jacket,tobacco_shop,pay-phone,vending_machine,bakery,mailbox
3,four-poster,fountain,bannister,lampshade,altar,stupa,palace,church,organ,theater_curtain
4,web_site,hand-held_computer,iPod,screen,cash_machine,cellular_telephone,menu,monitor,desktop_computer,laptop

In [4]:

#results = set()
#df['Prediction_1'].str.lower().str.split().apply(results.update)
#print results

count = df.groupby(['Prediction_1']).count() 
print(count)

              Prediction_2  Prediction_3  Prediction_4  Prediction_5  \
Prediction_1
0                        1             1             1             1
1                        1             1             1             1
2                        1             1             1             1
3                        1             1             1             1
4                        1             1             1             1
5                        1             1             1             1
6                        1             1             1             1
7                        5             5             5             5
8                        1             1             1             1
9                        1             1             1             1
10                       5             5             5             5
11                       1             1             1             1
12                       5             5             5             5
13                       1             1             1             1
14                       1             1             1             1
15                       1             1             1             1
16                       1             1             1             1
17                       2             2             2             2
18                       1             1             1             1
19                       1             1             1             1
20                       1             1             1             1
21                       1             1             1             1
22                       1             1             1             1
23                       2             2             2             2
24                       1             1             1             1
25                       3             3             3             3
26                       2             2             2             2
27                       1             1             1             1
28                       1             1             1             1
29                       1             1             1             1
...                    ...           ...           ...           ...
524                      1             1             1             1
525                     11            11            11            11
526                      1             1             1             1
527                      2             2             2             2
528                      1             1             1             1
529                      2             2             2             2
530                      1             1             1             1
531                      1             1             1             1
532                      1             1             1             1
533                      1             1             1             1
534                      1             1             1             1
535                      2             2             2             2
536                      2             2             2             2
537                      6             6             6             6
538                      1             1             1             1
539                     39            39            39            39
540                      1             1             1             1
541                      1             1             1             1
542                      1             1             1             1
543                     18            18            18            18
544                      5             5             5             5
545                      6             6             6             6
546                      2             2             2             2
547                      5             5             5             5
548                      1             1             1             1
549                      2             2             2             2
550                      1             1             1             1
551                      1             1             1             1
552                      2             2             2             2
553                      2             2             2             2

              Prediction_6  Prediction_7  Prediction_8  Prediction_9  \
Prediction_1
0                        1             1             1             1
1                        1             1             1             1
2                        1             1             1             1
3                        1             1             1             1
4                        1             1             1             1
5                        1             1             1             1
6                        1             1             1             1
7                        5             5             5             5
8                        1             1             1             1
9                        1             1             1             1
10                       5             5             5             5
11                       1             1             1             1
12                       5             5             5             5
13                       1             1             1             1
14                       1             1             1             1
15                       1             1             1             1
16                       1             1             1             1
17                       2             2             2             2
18                       1             1             1             1
19                       1             1             1             1
20                       1             1             1             1
21                       1             1             1             1
22                       1             1             1             1
23                       2             2             2             2
24                       1             1             1             1
25                       3             3             3             3
26                       2             2             2             2
27                       1             1             1             1
28                       1             1             1             1
29                       1             1             1             1
...                    ...           ...           ...           ...
524                      1             1             1             1
525                     11            11            11            11
526                      1             1             1             1
527                      2             2             2             2
528                      1             1             1             1
529                      2             2             2             2
530                      1             1             1             1
531                      1             1             1             1
532                      1             1             1             1
533                      1             1             1             1
534                      1             1             1             1
535                      2             2             2             2
536                      2             2             2             2
537                      6             6             6             6
538                      1             1             1             1
539                     39            39            39            39
540                      1             1             1             1
541                      1             1             1             1
542                      1             1             1             1
543                     18            18            18            18
544                      5             5             5             5
545                      6             6             6             6
546                      2             2             2             2
547                      5             5             5             5
548                      1             1             1             1
549                      2             2             2             2
550                      1             1             1             1
551                      1             1             1             1
552                      2             2             2             2
553                      2             2             2             2

              Prediction_10
Prediction_1
0                         1
1                         1
2                         1
3                         1
4                         1
5                         1
6                         1
7                         5
8                         1
9                         1
10                        5
11                        1
12                        5
13                        1
14                        1
15                        1
16                        1
17                        2
18                        1
19                        1
20                        1
21                        1
22                        1
23                        2
24                        1
25                        3
26                        2
27                        1
28                        1
29                        1
...                     ...
524                       1
525                      11
526                       1
527                       2
528                       1
529                       2
530                       1
531                       1
532                       1
533                       1
534                       1
535                       2
536                       2
537                       6
538                       1
539                      39
540                       1
541                       1
542                       1
543                      18
544                       5
545                       6
546                       2
547                       5
548                       1
549                       2
550                       1
551                       1
552                       2
553                       2

[554 rows x 9 columns]

In [3]:

#df[0] = pd.Categorical(df.Prediction_1)
#df['Prediction_1'] = pd.Categorical.from_array(dataframe.Prediction_1).codes
df['Prediction_1'] = df['Prediction_1'].astype('category')
df['Prediction_2'] = df['Prediction_2'].astype('category')
df['Prediction_3'] = df['Prediction_3'].astype('category')
df['Prediction_4'] = df['Prediction_4'].astype('category')
df['Prediction_5'] = df['Prediction_5'].astype('category')
df['Prediction_6'] = df['Prediction_6'].astype('category')
df['Prediction_7'] = df['Prediction_7'].astype('category')
df['Prediction_8'] = df['Prediction_8'].astype('category')
df['Prediction_9'] = df['Prediction_9'].astype('category')
df['Prediction_10'] = df['Prediction_10'].astype('category')

#df.dtypes
cat_columns = df.select_dtypes(['category']).columns
df[cat_columns] = df[cat_columns].apply(lambda x: x.cat.codes)
#df

coocc = df.T.dot(df)
coocc
#coocc.to_csv('to_gephi.csv', sep = ',')
#df.head()
#data = data.convert_objects(convert_numeric=True)
#df_asint = data.astype(int)
#coocc = df_asint.T.dot(df_asint)

,Prediction_1,Prediction_2,Prediction_3,Prediction_4,Prediction_5,Prediction_6,Prediction_7,Prediction_8,Prediction_9,Prediction_10
Prediction_1,-32753,-22570,-21013,1613,20065,6688,7672,-11221,25938,23443
Prediction_2,-22570,17534,17108,-22992,-8722,13181,-4022,11959,-2203,-14948
Prediction_3,-21013,17108,96,24250,19139,-5553,5199,-30749,-27539,4588
Prediction_4,1613,-22992,24250,27869,7808,21366,28512,9618,30689,-31740
Prediction_5,20065,-8722,19139,7808,25503,1305,14645,-6157,28662,6561
Prediction_6,6688,13181,-5553,21366,1305,15825,12063,28141,875,-8871
Prediction_7,7672,-4022,5199,28512,14645,12063,-18376,12235,916,-17699
Prediction_8,-11221,11959,-30749,9618,-6157,28141,12235,6830,30534,28918
Prediction_9,25938,-2203,-27539,30689,28662,875,916,30534,-4283,-12643
Prediction_10,23443,-14948,4588,-31740,6561,-8871,-17699,28918,-12643,6122